### ISSUE TITLE
How do you make the "Game Over " animation?  

### ISSUE THREAD

**Issue by KevinHu2014** [zmxv/alpha-reflex#2]
![alt tag](http://i.imgur.com/Ow3ksrJ.png)
How do you make the "Game Over " animation?

**Comment by KevinHu2014** [comment]
@zmxv Any details about how you make this ?

**Comment by zmxv** [comment]
I applied a "transform" animation to an overlay. I'll explain in detail with source code when I get to write the next tutorial.

**Comment by KevinHu2014** [comment]
Thanks!
Looking forward to it.
